version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sakila
      MYSQL_USER: sakila
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
        PMA_HOST: db
        PMA_USER: sakila
        PMA_PASSWORD: password
    ports:
        - 8080:80
    volumes:
      - phpmyadmin-data:/sessions
    platform: linux/x86_64
volumes:
  mysql-data:
  phpmyadmin-data:
