version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306" # port重複防止のため、local側は3306以外とする
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sakila
      MYSQL_USER: sakila
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sakila-db:/tmp/sakila-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
        PMA_HOST: db
        PMA_USER: sakila
        PMA_PASSWORD: password
    ports:
        - 8080:80
    volumes:
      - phpmyadmin-data:/sessions
    platform: linux/x86_64
volumes:
  mysql-data:
  phpmyadmin-data:
